[project]
name = "jianer-qq-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.18",
    "asyncio>=3.4.3",
    "datetime>=5.5",
    "emoji>=2.14.1",
    "flask>=3.1.0",
    "google-generativeai==0.7.2",
    "gputil>=1.4.0",
    "httpx>=0.28.1",
    "hyper-bot==0.78.2",
    "openai>=1.35.12",
    "paramiko>=3.5.1",
    "pillow>=11.2.1",
    "psutil>=7.0.0",
    "pyside6>=6.9.0",
    "pyside6-fluent-widgets>=1.7.7",
    "requests>=2.32.3",
    "websocket-client>=1.8.0",
]
